### ISSUE TITLE
Need a more organized folder structure. Remove files and folders which are not required. 

### ISSUE THREAD

**Issue by Fawke** [vinay-ravishankar/ES6-React-training#2]
- chicago-crime-assignment
    - data
        - input (don't commit this)
        - output (theft.json and assaut.json should come here)
     - parser.js (only 1 js for writing the parsing logic, for both the parts)
     - line-chart.html (for assault.json)
     - stacked-bar-chart.html (for crimes.json)

**Comment by vinay-ravishankar** [comment]
folder structure organized and committed in below link
https://github.com/vinay-ravishankar/ES6-React-training/tree/master/week1-assignment
